// Code generated by "stringer -type=ValidationError -output=error_string.go"; DO NOT EDIT.

package maritime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknown-50000]
	_ = x[ErrVesselIDOrShipIDRequired-50001]
	_ = x[ErrShipNameOrMMSIOrShipIDOrIMORequired-50002]
}

const _ValidationError_name = "ErrUnknownErrVesselIDOrShipIDRequiredErrShipNameOrMMSIOrShipIDOrIMORequired"

var _ValidationError_index = [...]uint8{0, 10, 37, 75}

func (i ValidationError) String() string {
	i -= 50000
	if i < 0 || i >= ValidationError(len(_ValidationError_index)-1) {
		return "ValidationError(" + strconv.FormatInt(int64(i+50000), 10) + ")"
	}
	return _ValidationError_name[_ValidationError_index[i]:_ValidationError_index[i+1]]
}
